conf/codedeployagent.yml
lib/instance_agent/config.rb
lib/instance_agent/plugins/codedeploy/codedeploy_control.rb
lib/instance_agent/plugins/codedeploy/command_executor.rb
test/instance_agent/config_test.rb

This adds a proxy_uri configuration option
This configuration option is useful/necessary because ruby does not automatically detect credentials for authenticated proxies from the `http_proxy` environment variable.  
It might be possible to do this without a configuration option by detecting the `http_proxy` environment variable, or using that value as a default.  I think an explicit configuration option is clearer and more powerful.
Where Seahorse clients are initialized, the http_proxy configuration option is now passed to them.
Certificate validation uses net/http, proxy settings are explicitly overridden if this configuration option is provided.

support for proxy_uri configuration option

---

bin/install

Add HTTP proxy support (new optional parameter)
Change the way S3 uri are generated: use virtual hosting (bucket in the hostname) to allow filtering on domain names

Add proxy support and change S3 uri to use virtual hosting

---

init.d/codedeploy-agent
lib/instance_agent/platform/linux_util.rb
lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb
lib/instance_agent/plugins/codedeploy/application_specification/script_info.rb
test/instance_agent/platform/linux_util_test.rb

Code Deploy,
This PR is meant to open a conversation around adding support for running hooks with sudo.  We have a requirement to run commands as sudo to provide additional logs to our operation center. There is also a secondary to desire to run the code deploy agent as a non-root user (if possible).
You can add now add sudo to hooks to have them executed with sudo:
```yaml
version: 0.0
os: linux
files:
- source: /index.html
destination: /var/www/html/
hooks:
BeforeInstall:
- location: scripts/install_dependencies
timeout: 300
runas: root
sudo: true
- location: scripts/start_server
timeout: 300
runas: root
sudo: true
ApplicationStop:
- location: scripts/stop_server
timeout: 300
runas: root
sudo: true
```
This has also been tested to allow for running the code deploy agent as a non root …

Add support for running hooks with sudo

---

init.d/codedeploy-agent

On centos 7.2, line 22 ends up wiping out the passed in param which always results in this output: `Usage: /etc/init.d/codedeploy-agent {start|stop|status|restart}`. Assigning it to a variable prior and using it in the switch statement get this working properly.

Assigning init.d script param to a variable

---

init.d/codedeploy-agent
init.d/codedeploy-agent.service
lib/instance_agent/platform/linux_util.rb
lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb
lib/instance_agent/plugins/codedeploy/application_specification/script_info.rb
lib/instance_agent/plugins/codedeploy/command_executor.rb
test/instance_agent/platform/linux_util_test.rb

@suryanarayanan this is the new PR with updated init scripts.  There is a new addition ./init.d/codedeploy-agent.service for RHEL 7 systems.  I wasn't able to get the process to start using the legacy script, so I created a systemd service file.  The intent is to replace /etc/init.d/codedeploy-agent on RHEL 7 systems with this new /etc/systemd/system/codedeploy-agent.service file.
Let me know what you think.

Add sudo support

---

vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb

The agent would fail to start if by chance the (stale) pidfile would reference an existing process with only *codedeploy* in its name string.
This is not that odd considering:
- The agent is set up to start at boot.
- That the stop process takes long enough so that when an instance is shut down it always leaves the pidfile behind (see related issue #55)
- The "@reboot" cronjob is sleeping for 45 seconds before executing */opt/codedeploy-agent/bin/install* wich contains **codedeploy** in the name of the process.
Add enough instances to the mix and you get this issue pretty often.
Just by checking for a more specific string in cmdline this can be avoided.

Improve process name check

---

init.d/codedeploy-agent.service

SysV script [invokes the agent with bash](https://github.com/aws/aws-codedeploy-agent/blob/eef9a73fa5dd715c4925fa9869e55204188177a6/init.d/codedeploy-agent#L1). Keep invoking the agent like that when using Systemd as /bin/sh can behave differently. Most notably it sets `POSIXLY_CORRECT=y` in CentOS (and also probably in RedHat)

Keep invoking the agent from bash when using systemd

---

vendor/gems/process_manager-0.0.13/lib/process_manager/master.rb

The codedeploy-agent.pid file sometimes remains for some reasons when os is shutdown. The new running agent could have the same process id as the process id in the pid file. As a result, the new one checks own process and self-terminate.
This will frequently occur if the boot order is always the same, and the number of processes launched from rc scripts is always the same.

changed process check to execulde own process id

---

init.d/codedeploy-agent.service

There are two reasons this is important:
1. Currently, if the service hits an error and stops, it will not be restarted by systemd.
2. If the service fails to start boot on an instance in an ASG, the instance may be left in a pending:wait state (due to the CodeDeploy ASG LifeCycle hooks) which means the instance could sit around broken for 60 minutes before the ASG will terminate it.

Restart on failure in systemd unit definition.

---

bin/codedeploy-agent

This check was not being maintained and has been failing with the latest
rubies.  It's not clear what the goal of this check was.
Addresses comment 1 in issue #90 in a passive manner.

Get rid of the upper bound ruby version check

---

init.d/codedeploy-agent.service

Adds a dependency to the network target. Aim is to avoid premature startup.
I'm not 100% sure this will fix *my* issue, but not specifying at least a basic dependency is not ok in any case.

add dependency to systemd unit

---

test/certificate_helper.rb

I was seeing random failures executing rake, and the failures mentioned PKCS7 validation errors. Looking at the helper, I saw the timeout was Time.now + 60, which seemed low. After changing it to +/-10000, I was able to execute 30+ tests in a row without failures.

Push back not_before, not_after times of test certificates

---

lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb

Added type(Array) test for hooks before parsing.
Updated hook['script']['location'] test from (is present && is not nil) to 'is string'.

Empty hooks in appspec

---

lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb

Fixing the following error:
```
Starting to execute deployment from within folder /opt/codedeploy-agent/deployment-root/default-local-deployment-application/d-J324JTGAR-local
/opt/codedeploy-local/gems/aws_codedeploy_agent-0.1/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:89:in `block in parse_permissions': uninitialized constant InstanceAgent::Plugins::CodeDeployPlugin::ApplicationSpecification::LinuxPermissionInfo (NameError)
from /opt/codedeploy-local/gems/aws_codedeploy_agent-0.1/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:84:in `each'
from /opt/codedeploy-local/gems/aws_codedeploy_agent-0.1/lib/instance_agent/plugins/codedeploy/application_specification/application_specification.rb:84:in …
```

Require all necessary plugins

---

lib/instance_agent/config.rb
lib/instance_agent/plugins/codedeploy/command_executor.rb
test/instance_agent/config_test.rb

The Code Deploy agent currently expects the Github API to be located at `https://api.github.com`.
For GitHub Enterprise users, this url could be at any other location (e.g. `https://development.my-company.com/api/v3`).
This pull request makes the api url configurable for people who want the agent to work with GHE. It should have no change to the default behavior.

Make `github_api_url` configurable

---

lib/instance_agent/plugins/codedeploy/deployment_specification.rb

This reverts commit 9d13f1b64a637510b0b253b44eefc3e5202d5279.
cr https://code.amazon.com/reviews/CR-2114105

Revert "Add back in the verification of the certs by open SSL library"

---

lib/instance_agent.rb
lib/instance_agent/platform/thread_joiner.rb
lib/instance_agent/plugins/codedeploy/hook_executor.rb
test/instance_agent/platform/thread_joiner_test.rb
test/instance_agent/plugins/codedeploy/hook_executor_test.rb

Here's a tentative fix for Issue #118. It's tested, and relatively simple. Other enhancements, like killing the STDOUT/STDERR pump threads when their joins time out, could easily be added.
A new error code, `OUTPUTS_LEFT_OPEN_CODE = 6`, is added to the `ScriptError` class. Presumably, this could be tied to information in the AWS Console for the failed event, possibly containing a link to helpful documentation?

Fix for #118 (agent hangs if STDOUT/STDERR left open by hook)

---

lib/instance_agent/plugins/codedeploy/hook_executor.rb

Prior to this change, The tests for windows were failing.
This change add the necessary require in the hook_executor file.
cr https://code.amazon.com/reviews/CR-2695179

Fix the hook execution windows tests

---

lib/aws/codedeploy/local/cli_validator.rb
spec/aws/codedeploy/local/cli_validator_spec.rb

Hi, I fixed minor typo in error messages.
Thanks 👍

Fixed typo

---

bin/install

As discussed in #109, here are the changes required for MRI 2.5 support.

Add MRI 2.5 to the known Ruby versions.

---

lib/instance_agent/platform/linux_util.rb
lib/instance_agent/platform/windows_util.rb
lib/instance_agent/plugins/codedeploy/command_executor.rb

Add Powershell script to unzip files.

Add unzip command option to handle bundles with zip format in Linux.

---

lib/instance_agent/plugins/codedeploy/install_instruction.rb
test/instance_agent/plugins/codedeploy/install_instruction_test.rb

This closes aws#185.
When installing ruby in `ubuntu 18.04`, ruby version `2.5.x` is installed by default.
Before ruby `2.5`(i.e., `2.4.3`), `FileUtils.rmdir` [silently fails when the target directory is not empty](https://ruby-doc.org/stdlib-2.4.3/libdoc/fileutils/rdoc/FileUtils.html#method-c-rmdir), so the non-empty directories in cleanup file are not removed on deployment, and the deployment succeeds. 
But the implementation of `FileUtils.rmdir` is [changed in ruby `2.5`](https://ruby-doc.org/stdlib-2.5.0/libdoc/fileutils/rdoc/FileUtils.html#method-c-rmdir) so that it doesn’t rescue `Errno::ENOTEMPTY` any more, which generates failures on deployment.
This PR adds a rescue from `Errno::ENOTEMPTY`, thus non-empty directories in cleanup file are not removed for ruby 2.5 and forward, and …

Ignore non-empty directories when cleanup

---

features/codedeploy-local/codedeploy_local.feature
features/step_definitions/codedeploy_local_steps.rb
lib/instance_agent/plugins/codedeploy/command_executor.rb

#Notes
We currently do this for archives produced by github but it seems generally useful (In particular, it would make the CodePipeline "My First Pipeline" tutorial simpler). This should not modify the behavior of anything that works now (modulo bugs)
#Testing
I created an integration test which runs successfully. I also successfully manually tested a prior version of this (with the same logic) in my own Deployment group.

If a bundle is an archive of a directory, strip the leading directory

---

README.md
bin/install
bin/update
codedeploy_agent.gemspec
features/codedeploy-agent/agent.feature
features/codedeploy-local/codedeploy_local.feature
features/step_definitions/agent_steps.rb
features/step_definitions/common_steps.rb
lib/instance_agent/plugins/codedeploy/application_specification/range_info.rb
lib/instance_agent/plugins/codedeploy/command_executor.rb
lib/instance_metadata.rb
lib/winagent.rb
test/instance_agent/plugins/codedeploy/codedeploy_control_test.rb
test/instance_agent/plugins/codedeploy/command_executor_test.rb
test/instance_metadata_test.rb
vendor/gems/codedeploy-commands-1.0.0/lib/aws/add_service_wrapper.rb
vendor/gems/codedeploy-commands-1.0.0/lib/aws/plugins/deploy_control_endpoint.rb

*Issue #, if available:* #272, #273
Releasing changes for the following commits:
- Fixed: 1.3.0 issue that prevented on-premises instances from starting.
- ~Fixed~ _See note below_: Issue that prevented Windows clients from communicating with VPC endpoints (AWS PrivateLink).
- Fixed: Removed an expired certificate that was no longer used.
- Fixed: Removed the prompt message from the agent uninstall script used by AWS Systems Manager, making it easier to downgrade a host or fleet to a previous version of the agent.
*Note on Windows VPC endpoint support*
This change includes a fix needed to address #272. However, due to a bug in how the resulting MSI is packaged, the patch was not picked up in the 1.3.1 public release. That will be expressed in the next release …

V1.3.1 Release

---

.github/workflows/ruby.yml
Gemfile
spec/spec_helper.rb
test/test_helper.rb

Adding GitHub Actions Workflow File.

Adds Workflow YAML file

---

.gitignore
Rakefile

This change introduces a new target (`rake package`) in the Rakefile for building a tar.gz of the code. 
To install the gems needed in packaging, use `bundle install --without=test development --path=./vendor-thirdparty`, then use `rake package`.

Adds Rakefile task to package

---

test/instance_agent/file_credentials_test.rb

This reverts commit 4b4aab1b0794d0363573240fcf81218257663703
Logic to preserve error was added here: 47e3fa58907a1afd11e6118b69919436965a4f1a
This should fix the 1.7.x failing action.
Verified by:
1. Locally updated ruby to 2.7 using rbenv (matching workflow expectation)
2. `bundle install`
3. `bundle exec rake`
```
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
445 tests, 1028 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
----------------------------------------------------------------------------------------------------------------------------- …
```

Revert "Updated expected error message in file_credentials_test"
